dist: xenial
sudo: false
language: python
python:
  - "3.5"
  - "3.9"

env:
  global:
    - secure: g/ta2yudfA55ruxd+GHxYQUd39OM/hoEhNp0KgPm3QINaXwaB6C9eQ31qOi/i9OiSjmVwISE+yUaPtQP2jtbYnkS/SHiRNvzhfA+mPrT0n0hoVSNIlxl94E8hoPBZr2jlYVQ6dIuT98mIRYJu/wiGHDQCuar6znpiKFB1/gyUszvZxAxHJIe5EcjuXWFnre91b96tNkZRKJZv+Jst0CkknVcKAZ4kmC/o5Z1hr5VaMekRV5SKf+vMEfVc+W9VktqDBgKwaFIwWqSgQFk5LOnPr/EZq8mrqPpa+LFaLiQpDGDAdaVEM0/A3dzx3YnYoBFNr5hmCtoCLWccxC+diaw3kZuTX6olxn8cbRCVf8lu4JuJKFU5CgTLS7NBH3Rpk4iRE7C9v4W+QKjw3CJxLCMoMqQCbYx6GjzjZYbZBA6jvaS6ZFe41N6egA0SpNvKtfYU9TR7lNVwGehRIY9kycOEX5ZQInkqILxz5YHrkMNfICdLY+rYFBDvgNAOZxYR1tLaOG9jYuUbBOLVRZz78wkPrXynquay6HZn7AxBxOdnvGQAkINvo40Lx/MWdZ88o3f/th838cpPCxBRQZ5Kn3RkHNhGHwUJadsbaOLnKrj3ISaTOvq0brA1mxJFyJwoVrn+rFs80CWRonQ5lQeaOHf0p1flH7j+TFhl/INkvXsf7Y=  # PGPASSWORD
    - secure: oV4B2TLhDLGs/LB1GdSbuoB451PUanfzA6jZU1Lb1oY2TC9DidjurGQ/w0SKFvuXSt0jzPrHQXlMA30sVBo9cYvFlhQ2MZYmaYvOCgMlR4ywujAyICNnox/kqZ9UPyGka384+yN0BR/4grWqi8f5HVV56kymT9/fMGh5Jn0ZfGnZgaIu/o63NbqbmctvJI64/25RshMuamsgnQEE0++mg1AngZR621ReXM98pzHgb85IiadhCL5OuK7dqD58s7MA/Wu6716U5PmDzUPp1kNGhxMNGW575Gv+DzTiqv2qNCKA0UjWVx10wFZIEoSraQcgXTpZG6tvnKpr7qtiVEoy0QNzdIYQVE9s856ZOwbssocOL3DAV+3FmVauMomRG4zFUo7SyE320FsuKgpq5l6nIoPPjkNC1udsZAtYFnTv0TcQIvDiFaT+b+riVW5SWc3EKI/Dp2AL4FcrCuc6BERyPRFXI2txq96btP3XTNo8w79KkcPfOavhhhfDTJCJlTwV2vuj5IEBskBsp0v0MFaTplsbT0KeB5xtfMvNmTuz3EfHwgqeZPQCzIKeLKW4dp5C5wGI+6F0GjQep/IgXU4eNxKF+zjQgenxsR8HPs4zWLDOSj+Yk7aNYyOLY18PHCx99mCEM+6yElNkP0d/SEzttIshLfRqIy+XPWPB0UL0MMc=  # VPCSECURITYGROUPID
    - secure: LQuEj3+bmS/zB5zZbOdcyF3Vv+UHi9O6cLtLG0BS6BbZIueaNomhbKuYklxKzTl6RsFrYh3y6yyi7cJqDxRxm11PT/rl5oXcu37JkheJrhqzNusNBaLdAUFyJQJmf7T1EO2GcYxR7zda7pcatP6v+2wx3ofPWBdfHCxnMORNED5u0dtSRGOJCUvA2xwPfIr1zTvEBTSjm7A1IiRr268lLwIW1apzW+OJKvJGtWcha4WsIXj0prBmA3D//9EcdnXIiApjfVXLOk5GXrr38CUW+c0+NR2Wea2l6Si32ZwKZSQcl4WaEATFUy+hzhOeoUZRINsUCK/ZKdkDRQsU87XQXqEJpSyz/lCtQyNJYdRhlJ0fvY1jxTQgijBXtk8X9E13L5GJ8hwxlBWzz+qcfFY22S21uPNdADGhIzNosT5RsaJI3DjIsQWctmLwe4RYQbr6w3vD9J0/xvx4heEyqKf5A+kShzJB6zjbHTdGWNG3RnsedNO7ZvMwqXt45j150h+h2IeCQmsK7qSVCirazWS4/B+nCUtzcOovDxX0p0SmNz4FUGaObvMDnr1NXK/1qbhy1InTfPrx+NLHAlIf23FdCz5deH7NFqqJWPCGCngNHXaSTUCfJk1l4bRsPXWz3zhO5JK4Gaow8SXguiaQHItJcF7zkkObsLOfxZ9DbCQ+sG0=  # IAMROLEARN
matrix:
  include:
    - python: "3.9"
      env: TOXENV=lint
    - python: "3.9"
      env: TOXENV=docs

install: pip install tox tox-travis
script: tox
cache: pip
